# Site settings
title: Jessica DeVriese
header-img: img/home-bg.jpg
email: jessdev@umich.edu
description: "I'm a software developer for R&D at Dow Chemical. This blog is for documenting the code/frameworks/etc for me and for you.'"
baseurl: ""
url: "https://jessdev.github.io"
twitter_username: JLSDevriese
github_username:  jessdev
email_username:  jessdev@umich.edu

# Google Analytics
# To enable google analytics, uncomment below line with a valid Google Tracking ID
# google_tracking_id:

#collections
#collections:
#  hobbies:
#    output: true

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md", ".gitignore"]

gems: [jekyll-paginate, jekyll-feed]
